#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CoffeeApp.Resource", IsApplication=true)]

namespace CoffeeApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int applogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int coffeeActionBar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Coffeemachine = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int disabledBeans = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int enabledBeans = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logoimage = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logsActionBar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int schedulesActionBar = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int settingsActionBar = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002a
			public const int ActiveCheckbox = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int ActiveLayout = 2131099689;
			
			// aapt resource value: 0x7f060043
			public const int Bbutton = 2131099715;
			
			// aapt resource value: 0x7f060035
			public const int ConnectButton = 2131099701;
			
			// aapt resource value: 0x7f06001f
			public const int DaysLayout = 2131099679;
			
			// aapt resource value: 0x7f060014
			public const int EditProfileTitle = 2131099668;
			
			// aapt resource value: 0x7f060042
			public const int Gbutton = 2131099714;
			
			// aapt resource value: 0x7f060034
			public const int IPeditText = 2131099700;
			
			// aapt resource value: 0x7f060033
			public const int IPtextView = 2131099699;
			
			// aapt resource value: 0x7f060044
			public const int OFFbutton = 2131099716;
			
			// aapt resource value: 0x7f06003c
			public const int OverviewUpdate = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int OverviewUpdateTxt = 2131099709;
			
			// aapt resource value: 0x7f060016
			public const int ProfileNameTxtLabel = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int ProfileTimeTxtLabel = 2131099673;
			
			// aapt resource value: 0x7f060041
			public const int Rbutton = 2131099713;
			
			// aapt resource value: 0x7f06001e
			public const int Space1 = 2131099678;
			
			// aapt resource value: 0x7f060028
			public const int Space2 = 2131099688;
			
			// aapt resource value: 0x7f060037
			public const int Starttime = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int Statusimg = 2131099704;
			
			// aapt resource value: 0x7f06001c
			public const int StayonforLabel = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int StayontimeTxtLabel = 2131099677;
			
			// aapt resource value: 0x7f060013
			public const int TitleLayout = 2131099667;
			
			// aapt resource value: 0x7f060046
			public const int aboutButton = 2131099718;
			
			// aapt resource value: 0x7f06002d
			public const int cancelButton = 2131099693;
			
			// aapt resource value: 0x7f060002
			public const int coffeeTextView = 2131099650;
			
			// aapt resource value: 0x7f060027
			public const int everydayTextView = 2131099687;
			
			// aapt resource value: 0x7f060024
			public const int fridayTextView = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int imageView1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int imageView2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int imageView3 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int imageView4 = 2131099658;
			
			// aapt resource value: 0x7f060040
			public const int ledtxt = 2131099712;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout2 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout3 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout4 = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout5 = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout6 = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int loadedProfilesTxt = 2131099661;
			
			// aapt resource value: 0x7f06002e
			public const int logListView = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int logid = 2131099695;
			
			// aapt resource value: 0x7f060032
			public const int logmsg = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int logtime = 2131099697;
			
			// aapt resource value: 0x7f060030
			public const int logtype = 2131099696;
			
			// aapt resource value: 0x7f06003e
			public const int mainUpdateIntervalTxt = 2131099710;
			
			// aapt resource value: 0x7f060020
			public const int mondayTextView = 2131099680;
			
			// aapt resource value: 0x7f060045
			public const int pininfoButton = 2131099717;
			
			// aapt resource value: 0x7f060015
			public const int profTimeLayout = 2131099669;
			
			// aapt resource value: 0x7f060036
			public const int profilename = 2131099702;
			
			// aapt resource value: 0x7f060017
			public const int profilenameEditText = 2131099671;
			
			// aapt resource value: 0x7f060039
			public const int profilesListView = 2131099705;
			
			// aapt resource value: 0x7f060018
			public const int proftimeLayout = 2131099672;
			
			// aapt resource value: 0x7f060025
			public const int saturdayTextView = 2131099685;
			
			// aapt resource value: 0x7f06002c
			public const int saveButton = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int savecancelLayout = 2131099691;
			
			// aapt resource value: 0x7f06003a
			public const int setting = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int soundToggleButton = 2131099707;
			
			// aapt resource value: 0x7f060010
			public const int statusTxtView = 2131099664;
			
			// aapt resource value: 0x7f06001b
			public const int stayonTimeLayout = 2131099675;
			
			// aapt resource value: 0x7f060026
			public const int sundayTextView = 2131099686;
			
			// aapt resource value: 0x7f06000f
			public const int sysTimeTxtView = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int tempTxtView = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int textView1 = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int textView2 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int textView3 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int textView4 = 2131099659;
			
			// aapt resource value: 0x7f060023
			public const int thursdayTextView = 2131099683;
			
			// aapt resource value: 0x7f06001a
			public const int timeLabel = 2131099674;
			
			// aapt resource value: 0x7f06003f
			public const int timeUpdateIntervalTxt = 2131099711;
			
			// aapt resource value: 0x7f060021
			public const int tuesdayTextView = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int wednesdayTextView = 2131099682;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Coffee = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CoffeeOverview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditProfile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Log = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LogOverview = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ProfileOverview = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Profiles = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Settings = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001e
			public const int Action1 = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int Action2 = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int Action3 = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int Action4 = 2130968609;
			
			// aapt resource value: 0x7f04000e
			public const int ApplicationName = 2130968590;
			
			// aapt resource value: 0x7f040015
			public const int Cancel = 2130968597;
			
			// aapt resource value: 0x7f040022
			public const int ClearlogButton = 2130968610;
			
			// aapt resource value: 0x7f04000c
			public const int ConnectButton = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int DefaultIP = 2130968591;
			
			// aapt resource value: 0x7f04001d
			public const int Everyday = 2130968605;
			
			// aapt resource value: 0x7f04001a
			public const int Friday = 2130968602;
			
			// aapt resource value: 0x7f040010
			public const int IPLabel = 2130968592;
			
			// aapt resource value: 0x7f040016
			public const int Monday = 2130968598;
			
			// aapt resource value: 0x7f040011
			public const int Profilename = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int Profiletime = 2130968594;
			
			// aapt resource value: 0x7f04001b
			public const int Saturday = 2130968603;
			
			// aapt resource value: 0x7f040014
			public const int Save = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int Stayontime = 2130968595;
			
			// aapt resource value: 0x7f04001c
			public const int Sunday = 2130968604;
			
			// aapt resource value: 0x7f040019
			public const int Thursday = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int Tuesday = 2130968599;
			
			// aapt resource value: 0x7f04000d
			public const int WaitingtoConnect = 2130968589;
			
			// aapt resource value: 0x7f040018
			public const int Wednesday = 2130968600;
			
			// aapt resource value: 0x7f040000
			public const int connectcode = 2130968576;
			
			// aapt resource value: 0x7f040024
			public const int defaultProfileView = 2130968612;
			
			// aapt resource value: 0x7f040003
			public const int deleteprofilecode = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int ledsoffcode = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int newprofilecode = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int requestlogscode = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int requestoverviewcode = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int requestprofilescode = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int requestsettings = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int requesttodaysprofiles = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int setcolorcode = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int switchoundcode = 2130968583;
			
			// aapt resource value: 0x7f040023
			public const int todaysProfilesView = 2130968611;
			
			// aapt resource value: 0x7f040002
			public const int updateprofilecode = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CustomActionBarTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyActionBar = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
